Спринт 14 версия 2
MoriYandex/java-shareit pull request #2
Opened 2023-10-26 12:36 UTC by MoriYandex

2023-10-26 17:33 UTC, EugeneLenkevich requested changes
Привет, Мориниллэ! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-10-26 17:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            " where b.item.owner = ?1" +
@Query("select b" +
            " from Booking b" +
            " where b.item.owner = :owner" +
            " order by b.start desc")

Все таки лучше использовать плейсхолдеры, а не номера переменный, так надежней и читается проще :)

2023-10-26 17:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b" +
`@Query(" from Booking b" + ....`

Можно кстати select не писать, такая вот более короткая запись :)

2023-10-26 17:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (bookingStatusDto) {
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2023-10-26 17:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/comment/service/CommentServiceImpl.java
> +            log.error(AUTHOR_NOT_FOUND_MESSAGE);
В лог бы добавить отладочной информации, потом же не найти к чему это сообщение относится, itemId, userId, в реальном приложении одновременно будут работать много пользователей, все сообщения будут вперемешку :)

2023-10-26 17:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking nextBooking = bookingList.stream()
Тут бы тоже сделать запрос в БД, который все необходимое, минимумы, максимумы, вытянет, получится? :)

2023-10-27 18:30 UTC, MoriYandex commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            " where b.item.owner = ?1" +
Отредактировал запросы.

2023-10-27 18:30 UTC, MoriYandex commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b" +
Сократил. Понравилось.

2023-10-27 18:31 UTC, MoriYandex commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (bookingStatusDto) {
Попробовав разные варианты, остановился на мапе функций. Приятно, спасибо.

2023-10-27 18:31 UTC, MoriYandex commented on src/main/java/ru/practicum/shareit/comment/service/CommentServiceImpl.java
> +            log.error(AUTHOR_NOT_FOUND_MESSAGE);
Добавил идентификаторов.

2023-10-27 18:35 UTC, MoriYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking nextBooking = bookingList.stream()
Без проблем сделал запросы для одиночной вещи. А вот для множества вещей...
1. Можно написать запрос оконной функцией. Но, насколько успел понять, JPQL не поддерживает конструкции вида select b from (select...). Без них получить минимумы и максимумы по фреймам - не очень представляю, как. Точнее, представляю, но запрос будет многоступенчатый и с многократным проходом по таблице. Плюс можно написать на нативном SQL - но это всё равно не избавить от необходимости фильтровать потом результат и по вещам, и по следующему и последнему.
2. Можно применить запрос к одиночной вещи для каждой вещи. Но нужно ли плодить запросы к базе, умножая их на количество вещей (проблема N + 1)? Если что, применить уже написанные запросы (они есть) мне не сложно.

2023-10-28 03:17 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking nextBooking = bookingList.stream()
Ок, пусть так остается не стоит сильно заморачиваться.
Ну и да, N+1 лучше избегать

2023-10-28 03:19 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо 

Здорово что получилось приделать стратегию, это достаточно распространенный паттерн :)

2023-10-31 16:08 UTC, merged